### PR TITLE
Create requirements.txt

### PR DESCRIPTION
**Pull request by eee555**
to support evf format

### CODE REVIEW

**Comment by ralokt** [comment]
Hi! First off, sorry for only replying to this now - only just noticed it, I don't check my GH notifications very often. In general, feel free to ping me on other channels if I don't respond on GH!

And thanks for offering a contribution here!

However: currently, this project is super simple - pure Python, with no dependencies (except the ones for building and testing, but users of the library don't care about that), and I'd like to keep it that way.

Even if reimplementing EVF in Python means duplicating a bit of code, I think it's worth it because it's not that much, it's consistent with the rest of the codebase, and it simplifies all projects that depend on it (including Scoreganizer).

Scoreganizer is a great example for why not having unnecessary dependencies matters to me - the server runs on Debian, and I try to customize as little as possible to keep the system maintainable. That means running the system Python version, for example. And I don't want to be in a situation where I'm unable to do a `dist-upgrade` because there's no wheel for `ms_toolkit` for the new Python version, so I have to build from source, so now I need to install the tooling to compile Rust, only to maybe discover that `ms_toolkit` needs a newer version of `rustc` than Debian provides, so now I have to manually install things and keep track of non-system packages, etc - you get the idea. Writing code is work, but dependencies can cause headaches, and I prefer a bit of work to headaches.

Also, just for the record - we're using `pyproject.toml` for dependency management here instead of a `requirements.txt`.

I understand if you don't feel like reimplementing EVF here - let me know your thoughts, from reading the `ms_toolkit` source code, I could probably also do it myself. Not sure yet when I'd get around to that, tho.

**Comment by eee555** [comment]
Reimplementing something is usually not a best practice because maintenance complexity increases and consistency is not guaranteed.

ms-toollib runs on any platform, including windows, linux, and mac, and performs consistently. It supports python 3.7-3.10. It can deel with any algorithmic problem about minesweeper.

It is practical to use the mstoollib.pyd file compiled from the source code. I'm leaning toward this option, too. This means that I don't have to maintain project dependencies, just import it, then use it. But that means anyone else will not use sweeping-view easily. Because committing the compiled results to the repository is not recommended.

In addition, the standard file for the evf format is this file:
[https://github.com/eee555/ms-toollib/blob/main/evf%E6%A0%87%E5%87%86.md](https://github.com/eee555/ms-toollib/blob/main/evf%E6%A0%87%E5%87%86.md)

**Comment by ralokt** [comment]
I'm gonna be a bit blunt here - not trying to be unfriendly, but I also want to make my point clearly.

> Reimplementing something is usually not a best practice because maintenance complexity increases and consistency is not guaranteed.

As I stated, I've considered the cost of having another implementation.

I consider DRY to be both one of the most fundamental guiding principles when it comes to writing maintainable code - as well as one of the ones with the most exceptions. I could go on a long tangent here - I did, but decided to edit it out because it was long and irrelevant, but I have it saved if you really wanna read it - but my point is:

I get where you're coming from, but also, if I reject a proposal based on other factors being more important than DRY, you're not gonna convince me by stating that DRY is a best practice, you'll have to argue why the benefits outweigh the downsides/why you think that my priorities are off/that I haven't considered something. I've been programming since very roughly 2005, you can assume that I know the basics.

> ms-toollib runs on any platform, including windows, linux, and mac, and performs consistently. It supports python 3.7-3.10. It can deel with any algorithmic problem about minesweeper.

`sweeping-view` currently supports Python 3.6-3.12. I'd consider dropping support for EOL versions, but in particular, introducing this dependency would make it impossible to use `sweeping-view` on any system python installation on an OS using the current version of Python, and even the one before that, too. Even Debian comes with Python 3.11 at this point. Besides Debian being a distribution that strongly emphasizes stability over having current versions of software, and therefore being a good example to make my point with, it's also what Scoreganizer runs on - so currently, `ms_toollib` is straight-up incompatible with Scoreganizer.

Also, `sweeping-view` doesn't aim to solve any algorithmic problems. It aims to extract basic metadata from minesweeper replays. Pulling `ms_toollib` in as a dependency is like shooting a mosquito with an assault rifle (which I'll admit does sound kinda appealing, if not at all wise).

> It is practical to use the mstoollib.pyd file compiled from the source code. I'm leaning toward this option, too. This means that I don't have to maintain project dependencies, just import it, then use it. But that means anyone else will not use sweeping-view easily. Because committing the compiled results to the repository is not recommended.

As long as there aren't wheels for all supported Python versions and all of windows/mac/linux+glibc, and current versions of Python aren't supported, it's a complete nonstarter to me. This isn't a promise that I'll change my mind if the wheels do exist, tho - nobody can guarantee that this will always be the case. But the only way I'm pulling in a non-critical dependency is if I can specify it as a requirement and it just works on the vast majority of systems.

> In addition, the standard file for the evf format is this file: https://github.com/eee555/ms-toollib/blob/main/evf%E6%A0%87%E5%87%86.md

Awesome, thanks! It's great that there's a standard document out there - all RMV has is an open source reference implementation by the clone maintainer, which isn't great, I should change that sometime 😅 Is there an English translation, by any chance (at least for that image containing text)?

**Comment by eee555** [comment]
My consistent position is not to convince you of what is right, but to provide you with comprehensive information that will help you make decisions.

> As long as there aren't wheels for all supported Python versions and all of windows/mac/linux+glibc, and current versions of Python aren't supported, it's a complete nonstarter to me.

ms_toollib can support python 3.7-3.12 after modifying the configuration.

There is a special mouse operation type "cc"(chording click) in the evf format, which did not appear in previous copies. Therefore, in order to be compatible with the content directly parsed from the evf (for example, when calculate lefts), the existing borad state machine needs to be modified. However, ms_toollib can parse avf, mvf, rmv, and evf, which shows that the borad state machine is complete and can be used without too many problems.

For example, the following code can work correctly in python.

``` python
import ms_toollib as ms
// AvfVideo, RmvVideo, MvfVideo, and EvfVideo
video = ms.EvfVideo(r"F:\GitHub\Solvable-Minesweeper\dist\Metaminesweeper-v3.1.9\replay\b_10_4.669_3BV=14_3BVs=2.999_匿名玩家(anonymous player).evf")
video.parse_video()
video.analyse()
video.current_time = 999.999 # set time to the end of the video

print(video.left)
print(video.right)
print(video.double)
print(video.left_s)
print(video.right_s)
print(video.double_s)
print(video.level)
print(video.cl)
print(video.cl_s)
print(video.ce)
print(video.ce_s)
print(video.bbbv)
print(video.bbbv_solved)
print(video.bbbv_s)
print(video.flag)
print(video.path)
print(video.time)  # the time shown on the counter currently
print(video.rtime) # game time, shown on leaderboard
print(video.etime) # the estimated time shown on the counter currently
print(video.video_start_time)
print(video.video_end_time)
print(video.mode)
print(video.software)
print(video.stnb)
print(video.corr)
print(video.thrp)
print(video.ioe)
print(video.is_official)
print(video.is_fair)
```

Reimplementing `video.parse_video()` is easy, while reimplementing `video.analyse()` is a little hard. Because dealing with "cc" is needed. 

What's more, ms_toollib performs the same in JavaScript/Typescript/nodejs (The size is 13 MB in Python and 300 KB in JavaScript.). 

For example, the following code can work correctly in JavaScript/Typescript.
For reference: [https://github.com/eee555/saolei_website/blob/bc12460a5a464f0c9448f922ec67975469e99424/front_end/src/views/UploadView.vue#L111-L146](https://github.com/eee555/saolei_website/blob/bc12460a5a464f0c9448f922ec67975469e99424/front_end/src/views/UploadView.vue#L111-L146)

``` js
const ms = await import("ms-toollib");
// read video file in buffer
let video_file_u8 = new Uint8Array(await video_file.arrayBuffer());
// just AvfVideo and EvfVideo, rmv will be accessible if you need.
video = ms.AvfVideo.new(video_file_u8, uploadFile.name);
video.parse_video();
video.analyse();
video.current_time = 999.999
console.log(video.get_left)
console.log(video.get_right)
console.log(video.get_left_s)
console.log(video.get_right_s)
console.log(video.get_double_s
console.log(video.get_level)
console.log(video.get_cl)
console.log(video.get_cl_s)
...
// Code autocomplete works here.
```

That’s the complete information I need to provide.

>  Is there an English translation, by any chance (at least for that image containing text)?

Of course, I will translate the whole text next.

**Comment by ralokt** [comment]
> My consistent position is not to convince you of what is right, but to provide you with comprehensive information that will help you make decisions.

And indeed you did, as I'll get into!

> ms_toollib can support python 3.7-3.12 after modifying the configuration.

I think that would be a great idea irrespective of what we decide to do here, tbh

> Since there is a special mouse operation type "cc"(chording click) in the evf format, which did not appear in previous clones. In order to be compatible with the content directly parsed from the evf (for example, when calculate lefts), the existing borad state machine needs to be modified. However, ms_toollib can parse avf, mvf, rmv, and evf, which shows that the borad state machine is complete and can be used without too many problems.

That's super nice, and pretty impressive! What exactly does `cc` do? Is it for chording using an input device that isn't the mouse?

> Reimplementing `video.parse_video()` is easy, while reimplementing `video.analyse()` is a little hard. Because dealing with "cc" is needed.

Here's the thing, though: For Scoreganizer, I only need to parse the video. I pretty much just need to be able to extract player fields, time, 3bv, and maybe a few other bits of trivial metadata. Scoreganizer doesn't care about the actual contents of the replay - `sweeping_view` doesn't do more than basic parsing for AVF, too.

Of course, there's the question if it wouldn't be useful for other potential users of `sweeping_view` if the library could do more. Then again, now, developers have a choice - a bare-bones pure python library that doesn't do a lot, but might do enough for their use case - or a fully-fledged library that gives them access to way more features, but is also way bigger and requires installing a binary package.

If we pull in `ms_toollib` here, the choice becomes... `ms_toollib`, or `ms_toollib` but in blue.

BUT - I see much better where you're coming from now. If we did need proper replay analysis, and needed to implement a Minesweeper engine as opposed to just replay parsing - yeah, that would justify pulling in the dependency here, too (or probably just switching Scoreganizer over to `ms_toollib` altogether instead).

Speaking of, as far as I can see, there's exactly one thing `sweeping_view` does that `ms_toollib` doesn't (unless I missed it) - which is defining MIME types. Which brings me to the question - what should the MIME type for EVF be? `application/x-metasweeper` maybe?

> What's more, ms_toollib performs the same in JavaScript/Typescript/nodejs (The size is 13 MB in Python and 300 KB in JavaScript.).

The size diff between JS/TS and Python is kinda funny - I guess you can see which of the two ecosystems is used to make web frontends that need to be as small as possible in order to not take forever to load? :D

I also appreciate the approach of using Rust to write a library, and then providing bindings to other languages - it's something I've been digging into at work. In fact, I may or may not have actually used a somewhat similar project to `ms_toollib` to teach myself Rust at work :)

> > Is there an English translation, by any chance (at least for that image containing text)?
> 
> Of course, I will translate the whole text next.

Awesome! \o/

What I'm strongly leaning towards based on what you wrote:
 - I'd adjust the README here and redefine the project scope, making it explicit that `sweeping-view` can only parse replays, and recommend that people who need proper analysis use `ms_toollib`'s python bindings instead (in fact, I'll probably do that at some point either way)
 - One of us would implement EVF here (but only parsing, not analysis)

What do you think?

**Comment by eee555** [comment]
the translated  evf format specification is open source here:
[https://github.com/eee555/ms-toollib/blob/main/evf%20format%20(evf%E6%A0%87%E5%87%86).md](https://github.com/eee555/ms-toollib/blob/main/evf%20format%20(evf%E6%A0%87%E5%87%86).md)

> That's super nice, and pretty impressive! What exactly does cc do? Is it for chording using an input device that isn't the mouse?

As stated in the specification, "cc" is similar to "l", "r", and "m".  These operation types are included because evf is a uniform format. However, they are not recommended, as not all parsers can handle such complex situations (even though ms_toollib can handle them).

> Here's the thing, though: For Scoreganizer, I only need to parse the video. I pretty much just need to be able to extract player fields, time, 3bv, and maybe a few other bits of trivial metadata. Scoreganizer doesn't care about the actual contents of the replay - sweeping_view doesn't do more than basic parsing for AVF, too.

Get it.

> Speaking of, as far as I can see, there's exactly one thing sweeping_view does that ms_toollib doesn't (unless I missed it) - which is defining MIME types. Which brings me to the question - what should the MIME type for EVF be? application/x-metasweeper maybe?

Yes, ms_toollib does not define it. Currently, our website uses the suffix of the file name to identify the video file type. Maybe using MIME types will be better. `application/x-metasweeper` really sounds good.

> One of us would implement EVF here (but only parsing, not analysis)

Yes. Overall, now I understand and agree with this technical solution. And this pr has met the conditions for closing. Thank you for your patient explanation. I look forward to our next collaboration.

**Comment by ralokt** [comment]
> the translated evf format specification is open source here: https://github.com/eee555/ms-toollib/blob/main/evf%20format%20(evf%E6%A0%87%E5%87%86).md

Amazing, thanks for the fast work!

> As stated in the specification, "cc" is similar to "l", "r", and "m". These operation types are included because evf is a uniform format. However, they are not recommended, as not all parsers can handle such complex situations (even though ms_toollib can handle them).

Makes sense! Now I'm curious about the edge cases you needed them for :D

> Yes, ms_toollib does not define it. Currently, our website uses the suffix of the file name to identify the video file type. Maybe using MIME types will be better. `application/x-metasweeper` really sounds good.

If you do, it would be great to keep those consistent for the rest of the formats, too - `sweeping_view` defines them here: https://github.com/ralokt/sweeping-view/blob/main/sweeping_view/mime_types.py

> Yes. Overall, now I understand and agree with this technical solution. And this pr has met the conditions for closing. Thank you for your patient explanation. I look forward to our next collaboration.

Awesome! You're welcome, thanks for listening and understanding :) Before I close this PR, do you want to implement it, or should I do it myself? I'm fine with both, just might take a bit if I do it. (Or it might not, if I spontaneously find some time).

PTY and I have been discussing getting EVF supported on Scoreganizer in time for GSC, which he said back then would happen in September at the earliest (and I couldn't find additional info) - I'd do my best to get it done before then either way (but also have the server side to figure out - tournament hosts should be able to decide which formats to allow, currently there are no restrictions - but since Scoreganizer was made as a platform that supports tournaments played on WR-official clones, I still want people to be able to host tournaments where games are restricted in that way).

**Comment by eee555** [comment]
"cc", "l", "r", and "m" is not needed, but they exist theoretically.

> If you do, it would be great to keep those consistent for the rest of the formats, too - sweeping_view defines them here: https://github.com/ralokt/sweeping-view/blob/main/sweeping_view/mime_types.py

In principle, we keep existing definitions consistent.

> do you want to implement it, or should I do it myself

One of our principles is not to repeat implementing a Scoreganizer, as long as it stays open and safe. In accordance with this principle, I will continue this work when necessary (specifically, to implement parsing of evf without dependent here). But there is no more plan at the moment.

**Comment by ralokt** [comment]
I'm working on it now, so I'll finally close this! :)

**Pull request closed without merging**
